export const ques = [
  {
    id: 2438,
    question: "How many balls are their in picture?",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/1.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "COUNT_AND_TELL",
    order: 1,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2440,
        choice: "2",
      },
      {
        id: 2441,
        choice: "4",
      },
      {
        id: 2442,
        choice: "5",
      },
      {
        id: 2443,
        choice: "3",
      },
    ],
    questionAnswer: {
      id: 2439,
      answer: "4",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2444,
    question: "Count Nos of Pencils",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/2.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "COUNT_AND_TELL",
    order: 2,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2446,
        choice: "6",
      },
      {
        id: 2447,
        choice: "7",
      },
      {
        id: 2448,
        choice: "8",
      },
      {
        id: 2449,
        choice: "5",
      },
    ],
    questionAnswer: {
      id: 2445,
      answer: "6",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2450,
    question: "What is the denomination of this coin",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/3.svg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "VALUE_OF_MONEY",
    order: 3,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2452,
        choice: "10p",
      },
      {
        id: 2453,
        choice: "25p",
      },
      {
        id: 2454,
        choice: "50p",
      },
      {
        id: 2455,
        choice: "75p",
      },
    ],
    questionAnswer: {
      id: 2451,
      answer: "25p",
    },
    questionType: "STRING_TYPE",
  },
  {
    id: 2456,
    question: "Which of the following option has 5 rupees note?",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/4.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "VALUE_OF_MONEY",
    order: 4,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2458,
        choice: "A",
      },
      {
        id: 2459,
        choice: "B",
      },
      {
        id: 2460,
        choice: "C",
      },
      {
        id: 2461,
        choice: "D",
      },
    ],
    questionAnswer: {
      id: 2457,
      answer: "B",
    },
    questionType: "STRING_TYPE",
  },
  {
    id: 2462,
    question: "Identify Number 23",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "NUMBER_IDENTIFICATION",
    order: 5,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2464,
        choice: "12",
      },
      {
        id: 2465,
        choice: "23",
      },
      {
        id: 2466,
        choice: "32",
      },
      {
        id: 2467,
        choice: "33",
      },
    ],
    questionAnswer: {
      id: 2463,
      answer: "23",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2468,
    question: "Identify Number 16",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "NUMBER_IDENTIFICATION",
    order: 6,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2470,
        choice: "6",
      },
      {
        id: 2471,
        choice: "1",
      },
      {
        id: 2472,
        choice: "16",
      },
      {
        id: 2473,
        choice: "61",
      },
    ],
    questionAnswer: {
      id: 2469,
      answer: "16",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2474,
    question: "Identify the picture from the option with 4 cherries ",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/7.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "PICTORIAL_COUNTING",
    order: 7,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2476,
        choice: "A",
      },
      {
        id: 2477,
        choice: "B",
      },
      {
        id: 2478,
        choice: "C",
      },
      {
        id: 2479,
        choice: "D",
      },
    ],
    questionAnswer: {
      id: 2475,
      answer: "C",
    },
    questionType: "STRING_TYPE",
  },
  {
    id: 2480,
    question: "Identify the tray from options with 8 eggs",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/8.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "PICTORIAL_COUNTING",
    order: 8,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2482,
        choice: "A",
      },
      {
        id: 2483,
        choice: "B",
      },
      {
        id: 2484,
        choice: "C",
      },
      {
        id: 2485,
        choice: "D",
      },
    ],
    questionAnswer: {
      id: 2481,
      answer: "C",
    },
    questionType: "STRING_TYPE",
  },
  {
    id: 2486,
    question: "How Many fishes are their in a picture?",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/9.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "PICTORIAL_COUNTING",
    order: 9,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2488,
        choice: "18",
      },
      {
        id: 2489,
        choice: "19",
      },
      {
        id: 2490,
        choice: "20",
      },
      {
        id: 2491,
        choice: "17",
      },
    ],
    questionAnswer: {
      id: 2487,
      answer: "18",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2492,
    question: "How Many Circles are their?",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/10.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "PICTORIAL_COUNTING",
    order: 10,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2494,
        choice: "12",
      },
      {
        id: 2495,
        choice: "13",
      },
      {
        id: 2496,
        choice: "14",
      },
      {
        id: 2497,
        choice: "15",
      },
    ],
    questionAnswer: {
      id: 2493,
      answer: "13",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2498,
    question: "What number comes before 10 , while counting?",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "REVERSE_COUNTING",
    order: 11,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2500,
        choice: "9",
      },
      {
        id: 2501,
        choice: "11",
      },
      {
        id: 2502,
        choice: "12",
      },
      {
        id: 2503,
        choice: "8",
      },
    ],
    questionAnswer: {
      id: 2499,
      answer: "9",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2504,
    question: "Which number comes after 24, while counting?",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "REVERSE_COUNTING",
    order: 12,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2506,
        choice: "23",
      },
      {
        id: 2507,
        choice: "25",
      },
      {
        id: 2508,
        choice: "41",
      },
      {
        id: 2509,
        choice: "10",
      },
    ],
    questionAnswer: {
      id: 2505,
      answer: "25",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2510,
    question: "Which number comes before 52, while counting?",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "REVERSE_COUNTING",
    order: 13,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2512,
        choice: "53",
      },
      {
        id: 2513,
        choice: "51",
      },
      {
        id: 2514,
        choice: "24",
      },
      {
        id: 2515,
        choice: "26",
      },
    ],
    questionAnswer: {
      id: 2511,
      answer: "51",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2516,
    question: "What is the value of 3 + 4",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "SINGLE_DIGIT_ADDITION",
    order: 14,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2518,
        choice: "6",
      },
      {
        id: 2519,
        choice: "8",
      },
      {
        id: 2520,
        choice: "9",
      },
      {
        id: 2521,
        choice: "7",
      },
    ],
    questionAnswer: {
      id: 2517,
      answer: "7",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2522,
    question: "How much is 8 + 3 ?",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "SINGLE_DIGIT_ADDITION",
    order: 15,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2524,
        choice: "9",
      },
      {
        id: 2525,
        choice: "10",
      },
      {
        id: 2526,
        choice: "11",
      },
      {
        id: 2527,
        choice: "12",
      },
    ],
    questionAnswer: {
      id: 2523,
      answer: "11",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2528,
    question: "How many are their together",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/16.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "PICTORIAL_ADDITION",
    order: 16,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2530,
        choice: "8",
      },
      {
        id: 2531,
        choice: "7",
      },
      {
        id: 2532,
        choice: "9",
      },
      {
        id: 2533,
        choice: "10",
      },
    ],
    questionAnswer: {
      id: 2529,
      answer: "8",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2534,
    question: "How many are these together",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/17.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "PICTORIAL_ADDITION",
    order: 17,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2536,
        choice: "15",
      },
      {
        id: 2537,
        choice: "16",
      },
      {
        id: 2538,
        choice: "17",
      },
      {
        id: 2539,
        choice: "18",
      },
    ],
    questionAnswer: {
      id: 2535,
      answer: "16",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2540,
    question: "Fill in the missing number 0__2",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "NUMBER_SERIES",
    order: 18,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2542,
        choice: "3",
      },
      {
        id: 2543,
        choice: "1",
      },
      {
        id: 2544,
        choice: "4",
      },
      {
        id: 2545,
        choice: "2",
      },
    ],
    questionAnswer: {
      id: 2541,
      answer: "1",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2546,
    question: "Fill in the missing numbers 23 _ _ 26?",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "NUMBER_SERIES",
    order: 19,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2548,
        choice: "23,24",
      },
      {
        id: 2549,
        choice: "24,25",
      },
      {
        id: 2550,
        choice: "25,26",
      },
      {
        id: 2551,
        choice: "27,28",
      },
    ],
    questionAnswer: {
      id: 2547,
      answer: "24,25",
    },
    questionType: "STRING_TYPE",
  },
  {
    id: 2552,
    question: "Fill in the missing numbers 71 _ _ _ 75 ?",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "NUMBER_SERIES",
    order: 20,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2554,
        choice: "71,72,73",
      },
      {
        id: 2555,
        choice: "23,25",
      },
      {
        id: 2556,
        choice: "72,73,74",
      },
      {
        id: 2557,
        choice: "56,57,99",
      },
    ],
    questionAnswer: {
      id: 2553,
      answer: "72,73,74",
    },
    questionType: "STRING_TYPE",
  },
  {
    id: 2558,
    question: "Add and answer",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/21.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "SINGLE_DIGIT_ADDITION",
    order: 21,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2560,
        choice: "14",
      },
      {
        id: 2561,
        choice: "15",
      },
      {
        id: 2562,
        choice: "16",
      },
      {
        id: 2563,
        choice: "17",
      },
    ],
    questionAnswer: {
      id: 2559,
      answer: "16",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2564,
    question: "Add and answer",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/22.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "SINGLE_DIGIT_ADDITION",
    order: 22,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2566,
        choice: "27",
      },
      {
        id: 2567,
        choice: "28",
      },
      {
        id: 2568,
        choice: "29",
      },
      {
        id: 2569,
        choice: "30",
      },
    ],
    questionAnswer: {
      id: 2565,
      answer: "29",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2570,
    question: "Add and answer",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/23.svg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "SINGLE_DIGIT_ADDITION",
    order: 23,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2572,
        choice: "87",
      },
      {
        id: 2573,
        choice: "88",
      },
      {
        id: 2574,
        choice: "89",
      },
      {
        id: 2575,
        choice: "90",
      },
    ],
    questionAnswer: {
      id: 2571,
      answer: "88",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2576,
    question: "Subtract the following",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/24.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "SINGLE_DIGIT_SUBTRACTION",
    order: 24,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2578,
        choice: "4",
      },
      {
        id: 2579,
        choice: "5",
      },
      {
        id: 2580,
        choice: "6",
      },
      {
        id: 2581,
        choice: "7",
      },
    ],
    questionAnswer: {
      id: 2577,
      answer: "6",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2582,
    question: "Subtract the following",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/25.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "SINGLE_DIGIT_SUBTRACTION",
    order: 25,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2584,
        choice: "51",
      },
      {
        id: 2585,
        choice: "61",
      },
      {
        id: 2586,
        choice: "53",
      },
      {
        id: 2587,
        choice: "63",
      },
    ],
    questionAnswer: {
      id: 2583,
      answer: "51",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2588,
    question: "Subtract the following",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/26.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "SINGLE_DIGIT_SUBTRACTION",
    order: 26,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2590,
        choice: "15",
      },
      {
        id: 2591,
        choice: "5",
      },
      {
        id: 2592,
        choice: "25",
      },
      {
        id: 2593,
        choice: "35",
      },
    ],
    questionAnswer: {
      id: 2589,
      answer: "5",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2594,
    question: "Which has more?",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/27.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "COMPARISON",
    order: 27,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2596,
        choice: "A",
      },
      {
        id: 2597,
        choice: "B",
      },
    ],
    questionAnswer: {
      id: 2595,
      answer: "B",
    },
    questionType: "STRING_TYPE",
  },
  {
    id: 2598,
    question: "Which has fewer?",
    hasImage: true,
    imageUrl: "https://phd-data-bucket1.s3.amazonaws.com/6-grade/28.jpg",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "COMPARISON",
    order: 28,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2600,
        choice: "A",
      },
      {
        id: 2601,
        choice: "B",
      },
    ],
    questionAnswer: {
      id: 2599,
      answer: "B",
    },
    questionType: "STRING_TYPE",
  },
  {
    id: 2602,
    question:
      "My brother gave me 5 toffees. Next day he gave me 7 more. Now how many toffees do I have in total?",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "STATEMENT_PROBLEM_ADDITION_AND_SUBTRACTION",
    order: 29,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2604,
        choice: "5",
      },
      {
        id: 2605,
        choice: "7",
      },
      {
        id: 2606,
        choice: "12",
      },
      {
        id: 2607,
        choice: "13",
      },
    ],
    questionAnswer: {
      id: 2603,
      answer: "12",
    },
    questionType: "INTEGER_TYPE",
  },
  {
    id: 2608,
    question:
      "My teacher gave me 10 notebooks. She has taken 4 back from me. How many notebooks are left with me now?",
    hasImage: false,
    imageUrl: "",
    moduleType: "MODULE_2",
    ageCategory: "AGE_SIX",
    module1QuestionCategory: null,
    module2QuestionCategory: "STATEMENT_PROBLEM_ADDITION_AND_SUBTRACTION",
    order: 30,
    level: 1,
    attempt: null,
    questionChoicesList: [
      {
        id: 2610,
        choice: "9",
      },
      {
        id: 2611,
        choice: "5",
      },
      {
        id: 2612,
        choice: "6",
      },
      {
        id: 2613,
        choice: "7",
      },
    ],
    questionAnswer: {
      id: 2609,
      answer: "6",
    },
    questionType: "INTEGER_TYPE",
  },
];
